### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by ognjen011** [arcturial/clickatell-python#9]
Hello,

i am using your library but same like your example  but i have just added 3 arguments for a script to take. it used to run without problems but lately i'm seeing this issue:

to=sys.argv[1]
subject=sys.argv[2]
content=sys.argv[3]

then to send a message:

clickatell = Rest(token);
response = clickatell.sendMessage([to],content)

error:

Traceback (most recent call last):
  File "./clickatellsms.py", line 13, in <module>
    response = clickatell.sendMessage([to],content)
  File "/usr/local/lib/python2.7/dist-packages/clickatell/rest/__init__.py", line 40, in sendMessage
    content = self.parseResponse(self.request('messages', data, {}, 'POST'));
  File "/usr/local/lib/python2.7/dist-packages/clickatell/__init__.py", line 45, in parseResponse
    response['error'] = response['body']['error']
KeyError: 'error'

Any help?

**Comment by Kapooral** [comment]
Hello,
I had the same problem. We must replace

response['error'] = response['body']['error'] by  response['error'] = response['body']**['messages'][0]**['error']

in the __init__ file on line 45

**Comment by Kapooral** [comment]
Hello,
I had the same problem. I fixed it by replacing

response['error'] = response['body']['error'] by response['error'] = response['body']**['messages'][0]**['error']

in the __ init __ file of clickatell package on line 45
